### ISSUE TITLE
Scrolling to a page

### ISSUE THREAD

**Issue by Momeks** [sumitlni/LNICoverFlowLayout#11]
Hello  , I am trying to programmatically scroll collection view to a specific cell or better to say page, there is a problem with scrolling which is when collection view scrolls to a page the current cover is not fully centered and it has some degree ! 

![screen shot 2017-08-25 at 7 15 08 pm](https://user-images.githubusercontent.com/113414/29718989-c5baa4e4-89c9-11e7-9f69-7ed9b03733ea.jpg)

Here is my code 
 `  let indexPath = IndexPath(row: track, section: 0)
        collectionView.scrollToItem(at: indexPath, at: .left , animated: true)`

How can I fix this issue ?

**Comment by hons82** [comment]
Hi @Momeks, 
~~How did you solve this at the end?~~

[Ok, got it](https://stackoverflow.com/a/43716109/192976)
