### ISSUE TITLE
Image doesn't appear when only one item in collection.

### ISSUE THREAD

**Issue by rcutshaw** [sumitlni/LNICoverFlowLayout#15]
Issue #8 was fixed by gstrobl17 to fix a crash when there is only one item in the collection.  With this fix, however, the first item's image does not show up in the UI.  I fixed the section of code beginning at line 230 so that the image appears properly with only one item in the collection.  I'd like to submit the fix via a pull request, but am prohibited from creating a new request in your repository.  Please advise.  rcutshaw@cutshaw.com

**Comment by sumitlni** [comment]
I have made you a collaborator, you should now be able to push changes. Please do not push to master branch until you have also written tests to confirm other things don't break.

**Comment by rcutshaw** [comment]
Can I create a branch called ‘test’ and push to that branch?

Randy

**Comment by sumitlni** [comment]
Yes that is fine.

**Comment by sumitlni** [comment]
Thanks for the fix, looks reasonable.

**Comment by rcutshaw** [comment]
Thank you.
