### ISSUE TITLE
No Cell For Solo Item

### ISSUE THREAD

**Issue by gstrobl17** [sumitlni/LNICoverFlowLayout#8]
If there is only one item in the collection view, the solitary cell is not rendered.

Suggested fix: in func indexPathsContainedInRect(_ rect:CGRect)->[IndexPath] change conditional for generating the array of index paths to  "if minRow < maxRow || noI == 1 {"

**Comment by sumitlni** [comment]
Fixed in 1.0.1. Thanks for the suggested fix, worked fine.

**Comment by sumitlni** [comment]
Greg, FYI I have added you as a collaborator in case you run into further issues and would like to push changes directly. Please do not attempt push into master, create a separate branch. Thanks

**Comment by ZCOEngineer** [comment]
issue still there in 1.0.2

**Comment by ledyba-z** [comment]
It looks completely fixed at current master branch! (but not uploaded to CocoaPods yet)

@sumitlni Please would you update CocoaPods with the current master branch?
