### ISSUE TITLE
Additional check needed for Issue #8

### ISSUE THREAD

**Issue by mgnt** [sumitlni/LNICoverFlowLayout#9]
I've discovered an issue with the solution for https://github.com/sumitlni/LNICoverFlowLayout/issues/8 - in the event that `maxRow` is 0 but `noI` is 1, there will be a range exception in the subsequent for loop: `fatal error: Can't form Range with upperBound < lowerBound`. 

This can happen if the collection view width is less than 0.

I believe the solution is to include an additional check at line 231 like

```
if maxRow > 0 && (minRow < maxRow || noI == 1) {
```

**Comment by sumitlni** [comment]
I think I'd better do a sanity check on the range itself instead of throwing a fatal error. Let me check - how do you recreate this issue? By creating a collection view of width less than zero?

**Comment by mgnt** [comment]
In my case it's a collection view that gets animated to a width less than zero, but I believe creating one outright with less than zero width would trigger the crash, too.

**Comment by mgnt** [comment]
Hi, just checking on this… Any issues with the associated PR?

**Comment by sumitlni** [comment]
Closed with 1.0.2, out now.

**Comment by iPhonig** [comment]
> Closed with 1.0.2, out now.

This shouldn't be closed as the issue still persists. This however, is the correct fix. `(maxRow > 0 && minRow < maxRow) || noI == 1`
